# Generated by Django 4.2.3 on 2023-07-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_remove_usuario_dirección_alter_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
